"""Add survey API fields

Revision ID: 1dc686fd8ef8
Revises: 
Create Date: 2025-08-25 21:29:57.604099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc686fd8ef8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('text_answer', sa.Text(), nullable=True))
    op.add_column('answers', sa.Column('number_answer', sa.Integer(), nullable=True))
    op.add_column('answers', sa.Column('boolean_answer', sa.Boolean(), nullable=True))
    op.add_column('questions', sa.Column('is_required', sa.Boolean(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('questions', 'is_required')
    op.drop_column('answers', 'boolean_answer')
    op.drop_column('answers', 'number_answer')
    op.drop_column('answers', 'text_answer')
    # ### end Alembic commands ###
